### PR TITLE
Fix 1.17 support

### PR DESCRIPTION
**Pull request by ElectrumIsPog**
This adds 1.17 support to atlas.

### CODE REVIEW

**Comment by retrooper** [comment]
Thank you! I really wanted to use Atlas on my 1.17 server.

**Comment by Etheride** [comment]
PLEASE PUSH THIS MERGE
I WANT TO USE ATLAS ON MY 1.17 SMP THANK YOU!

**Comment by RenderPipelineExt** [comment]
Please merge this ASAP! We need 1.17 support

**Comment by NightSling** [comment]
Bump! Really useful pull request.. MERGE THIS ASAP!!

**Comment by funkemunky** [comment]
I appreciate the meme but Im working on the 1.17 update, no need to replace the Atlas repo with packetevents kek

**Comment by retrooper** [comment]
Bump

**Comment by ElectrumIsPog** [comment]
Bump, reopen this ASAP

**Pull request closed without merging**
